resource_group_name      = "rg-devops-dev"
vm_name                  = "vm-dev"
location                 = "westeurope"
key_vault_name           = "my-keyvault-dev"
key_vault_resource_group = "rg-secrets"
environment = "dev"