resource_group_name = "rg-devops-prod"
vm_name             = "vm-prod"
location                 = "westeurope"
key_vault_name           = "my-keyvault-prod"
key_vault_resource_group = "rg-secrets"
environment = "prod"