resource_group_name = "rg-devops-test"
vm_name             = "vm-test"
location                 = "westeurope"
key_vault_name           = "my-keyvault-test"
key_vault_resource_group = "rg-secrets"
environment = "test"
